### ISSUE TITLE
Module ignoring port mappings

### ISSUE THREAD

**Issue by pydo** [cloudposse/terraform-aws-ecs-container-definition#29] opened 2019-05-02 19:40 UTC
**Description**
Creating a container definition with  `port_mappings` and then removing the mapping doesn't work

**Repro steps**
1. Create a container definition with `port_mappings` defined:
Example:
```
module "aws_ecs_container_definition" {
  source          = "git::https://github.com/cloudposse/terraform-aws-ecs-container-definition.git?ref=master"
  container_name = "somecontainer"
  container_image = "5435345345346.dkr.ecr.us-east-1.amazonaws.com/app-blabla:${terraform.workspace}"
  container_cpu = 512
  //  essential = true

  command = [
    "/bin/bash",
    "bin/start.sh"]

  # hard limit
  container_memory = 2048

  # soft limit
  container_memory_reservation = 1024

  log_options = {
    awslogs-group = "${data.terraform_remote_state.global_resources.ecs_cloudwatch_log_group_name}",
    awslogs-region = "us-east-1",
    awslogs-stream-prefix = "someapp"
  }

  mount_points = [
    {
      containerPath = "${var.efs_cache_path}"
      sourceVolume = "${var.efs_cache_volume}"
    }
  ]

  environment = [
    {
      name = "AWS_ENVIRONMENT"
      value = "${terraform.workspace}"
    },
  ]
  port_mappings = [
    {
      hostPort = 80
      containerPort = 80
      protocol = "tcp"
    }
  ]
}
```
2. Remove said port_mappings and run `terraform plan -out=plan.out`

**Expected behaviour**
Terraform detects the change in the task_definition

**Actual behaviour**
No change is detected

**Comment by pydo** [comment] 2019-05-02 19:42
Setting the `port_mappings = []` to an empty list is a workaround. Terraform is able to detect this change.

**Comment by aknysh** [comment] 2019-05-03 17:43
thanks @pydo 
is it something that can be fixed?
maybe a note in README?

**Comment by pydo** [comment] 2019-05-04 13:12
@aknysh I'll try debugging the issue a bit more by looking at the JSON payload that is generated with an empty `port_mappings`.
If I don't find anything useful then I guess a note a the README would suffice.

**Comment by nitrocode** [comment] 2020-06-14 20:35
This seems like a duplicate of https://github.com/cloudposse/terraform-aws-ecs-container-definition/issues/74.

Do you mind retesting this @pydo?

**Closed** 2020-06-19 23:07 UTC
